#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: "us,he"
  timezone: America/Los_Angeles
  source:
    id: ubuntu-desktop-minimal
  storage:
    swap:
      size: 8
    config:
      - type: disk
        id: main
        match:
          ssd: true
          size: largest
  users:
    - name: dchid
      groups: sudo
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: # Don't enter passwords here, instead use hashed values.
      shell: /bin/bash
      home: /home/dchid
  packages:
    - build-essential
    - alacritty
    - eza
    - git
    - curl
    - cmus
    - duf
    - gh
    - bison
    - wget
    - fdupes
    - fish
    - bat
    - feh
    - jq
    - mpv
    - ncal
    - net-tools
    - neofetch
    - neovim
    - nmap
    - nodejs
    - npm
    - qalc
    - flatpak
    - ffmpeg
    - rustup
    - sd
    - tre-command
  late-commands:
    - apt update
    - apt upgrade -y
    - apt autoremove -y
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    - nvim "+PlugInstall"
    - rustup default stable
    - cargo install bk bottom du-dust
    - sudo chsh -s /bin/fish
  - shutdown: reboot
